version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.34.0
    container_name: prometheus_server
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      my_network:
        ipv4_address: 172.25.0.10

  node_exporter:
    image: prom/node-exporter:v1.2.2
    container_name: node_exporter_server
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      my_network:
        ipv4_address: 172.25.0.11

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Password123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      my_network:
        ipv4_address: 172.25.0.13

volumes:
  grafana_data:

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16

